# Generated by Django 2.0.4 on 2018-09-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_mensual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_mensual',
            name='sueldo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
