# Generated by Django 2.0.4 on 2018-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_mensual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto_general',
            name='if_default',
            field=models.BooleanField(default=False),
        ),
    ]
