# Generated by Django 2.0.4 on 2018-10-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_mensual', '0002_gasto_general_if_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
