# Generated by Django 2.0.4 on 2018-09-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_mensual', '0002_auto_20180911_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_mensual',
            name='sueldo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
