# Generated by Django 2.0.4 on 2018-10-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_mensual', '0003_sobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto_general',
            name='sobre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan_mensual.Sobre'),
            preserve_default=False,
        ),
    ]
