# Generated by Django 2.0.4 on 2018-07-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180726_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url_image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
